info:
  app:
    name: zabud-cv-core-ms
    description: Hojas de Vida Application
    version: 1.0.0
    encoding: UTF-8
    java:
      version: 1.17.0
spring:
  profiles.on-profile: ${ZABUD_ENV}
  autoconfigure:
    mvc:
      pathmatch:
        matching-strategy: ant-path-matcher
  datasource:
    url: jdbc:postgresql://${PG_DB_HOST_LOCAL}:${PG_DB_PORT_LOCAL}/${PG_DB_NAME_LOCAL_FLYWAY}
    username: ${PG_DB_USERNAME_LOCAL}
    password: ${PG_DB_PASSWORD_LOCAL}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      format-sql: true
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    sql:
      init:
        mode: always
    feign-clients:
    files:
      url: http://${FILE_MANAGER_HOST}:${FILE_MANAGER_PORT}/files-manager
    server:
      error:
        include-stacktrace: never
    flyway:
      baselineOnMigrare: true
      validate-on-migrate: false
      schemas: zabud,unicolombo,colombo
      createSchemas: true
      locations: db/migration
  flyway:
        enabled: true
multitenant:
  schemas: zabud,unicolombo,colombo
  package: zabud-cv-core-ms
logging:
  level:
    org:
      springframework: INFO
      hibernate:
        SQL: TRACE
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

